<?php

namespace Codelty\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * metricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class metricRepository extends EntityRepository
{
}
