<?php

namespace Codelty\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * metricTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class metricTypeRepository extends EntityRepository
{
}
